name = str(input("Enter your name"))
age= int(input("Enter your age"))
adress= str(input("Enter your adress"))
print(f"Your name is {name}")
print("Your age is" , age)
print("You live in " + adress)
