firstname = str(input("Enter your first name"))
lastname = str(input("Enter your last name"))
age= int(input("Enter your age"))
phonenumber= str(input("Enter your phone number"))
print('Your name is', firstname, lastname )
print("Your age is" , age)
print("Your phone number is " + phonenumber)
